(function(g){var window=this;'use strict';var UVa=function(a,b){return g.Ne(a,b)},VVa=function(a,b){b=b instanceof g.Of?b:g.Uf(b,/^data:image\//i.test(b));
a.src=g.Pf(b)},Y6=function(a){g.kl(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ra()).toString(36));
return a},Z6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Il(a.u,b,c)},WVa=function(a){if(a===g.Ip)throw Error("ES6 Iteration protocol does NOT adjust control flow when StopIteration is thrown from callback helper functions. If your code relies on this behavior, consider throwing a different error and catching it to terminate iteration.");
throw a;},XVa=function(a){if(a instanceof g.Gp)return a;
if("function"==typeof a.Lg)return a.Lg(!1);if(g.La(a)){var b=0,c=new g.Gp;c.next=function(){for(;;){if(b>=a.length)return g.j2;if(b in a)return g.Hp(a[b++]);b++}};
var d=c.next;c.Hj=function(){return g.Jp(d.call(c))};
return c}throw Error("Not implemented");},YVa=function(a,b,c){if(g.La(a))try{g.mc(a,b,c)}catch(e){WVa(e)}else for(a=XVa(a);;){var d=void 0;
try{d=a.Hj()}catch(e){if(e===g.Ip)break;throw e;}try{b.call(c,d,void 0,a)}catch(e){WVa(e)}}},ZVa=function(a,b){var c=[];
YVa(b,function(d){try{var e=g.Ms.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.tfa(e)&&c.push(d)},a);
return c},$Va=function(a,b){ZVa(a,b).forEach(function(c){g.Ms.prototype.remove.call(this,c)},a)},aWa=function(a){if(a.xa){if(a.xa.locationOverrideToken)return{locationOverrideToken:a.xa.locationOverrideToken};
if(null!=a.xa.latitudeE7&&null!=a.xa.longitudeE7)return{latitudeE7:a.xa.latitudeE7,longitudeE7:a.xa.longitudeE7}}return null},bWa=function(a,b){g.Ub(a,b)||a.push(b)},$6=function(a){var b=0,c;
for(c in a)b++;return b},cWa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},a7=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return cWa(a)},dWa=function(a,b,c,d){var e=new g.cl(null,void 0);
a&&g.dl(e,a);b&&g.el(e,b);c&&g.fl(e,c);d&&(e.K=d);return e},b7=function(a,b){g.Kv[a]=!0;
var c=g.Iv();c&&c.publish.apply(c,arguments);g.Kv[a]=!1},c7=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.us;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",eWa(this,a.capabilities||""),fWa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},eWa=function(a,b){a.capabilities.clear();
g.hq(b.split(","),g.Qa(UVa,gWa)).forEach(function(c){a.capabilities.add(c)})},fWa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},d7=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},e7=function(a,b){return!!b&&(a.id==b||a.uuid==b)},hWa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},iWa=function(a){return new d7(a)},jWa=function(a){return Array.isArray(a)?g.Vn(a,iWa):[]},f7=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},g7=function(a){return Array.isArray(a)?"["+g.Vn(a,f7).join(",")+"]":"null"},h7=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},kWa=function(a){return g.Vn(a,function(b){return{key:b.id,
name:b.name}})},i7=function(a,b){return g.Rb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},j7=function(a,b){return g.Rb(a,function(c){return e7(c,b)})},lWa=function(){var a=(0,g.Oy)();
a&&$Va(a,a.i.Lg(!0))},k7=function(){var a=g.Ry("yt-remote-connected-devices")||[];
g.jc(a);return a},mWa=function(a){if(g.Wb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Vn(a,function(d,e){return 0==e?d:d.substring(c.length)})},nWa=function(a){g.Qy("yt-remote-connected-devices",a,86400)},m7=function(){if(l7)return l7;
var a=g.Ry("yt-remote-device-id");a||(a=h7(),g.Qy("yt-remote-device-id",a,31536E3));for(var b=k7(),c=1,d=a;g.Ub(b,d);)c++,d=a+"#"+c;return l7=d},n7=function(){var a=k7(),b=m7();
g.Ub(a,b);g.Ty()&&g.lc(a,b);a=mWa(a);if(g.Wb(a))try{g.Mia("remote_sid")}catch(c){}else try{g.Mu("remote_sid",a.join(","),-1)}catch(c){}},oWa=function(){return g.Ry("yt-remote-session-browser-channel")},pWa=function(){return g.Ry("yt-remote-local-screens")||[]},qWa=function(){g.Qy("yt-remote-lounge-token-expiration",!0,86400)},rWa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Vn(pWa(),function(d){return d.loungeToken}),c=g.Vn(a,function(d){return d.loungeToken});
g.Wn(c,function(d){return!g.Ub(b,d)})&&qWa();
g.Qy("yt-remote-local-screens",a,31536E3)},sWa=function(a,b){g.Qy("yt-remote-session-browser-channel",a);
g.Qy("yt-remote-session-screen-id",b);a=k7();b=m7();g.Ub(a,b)||a.push(b);nWa(a);n7()},o7=function(a){a||(g.Sy("yt-remote-session-screen-id"),g.Sy("yt-remote-session-video-id"));
n7();a=k7();g.Zb(a,m7());nWa(a)},tWa=function(){if(!p7){var a=g.Vs();
a&&(p7=new g.Js(a))}},uWa=function(){tWa();
return p7?!!p7.get("yt-remote-use-staging-server"):!1},q7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},vWa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},wWa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},r7=function(a){a.length?xWa(a.shift(),function(){r7(a)}):s7()},yWa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},xWa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.xk(d,g.zs(a));(document.head||document.documentElement).appendChild(d)},zWa=function(){var a=q7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},s7=function(){var a=wWa();
a&&a(!1,"No cast extension found")},t7=function(){if(AWa){var a=2,b=wWa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;xWa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",s7,c)}},BWa=function(){t7();
var a=zWa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},DWa=function(){t7();
var a=zWa();a.push.apply(a,g.v(CWa.map(yWa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},u7=function(a,b,c){g.G.call(this);
this.I=null!=c?(0,g.E)(a,c):a;this.Wf=b;this.D=(0,g.E)(this.VQ,this);this.i=!1;this.u=0;this.B=this.Mb=null;this.C=[]},v7=function(a,b,c){g.G.call(this);
this.C=null!=c?a.bind(c):a;this.Wf=b;this.B=null;this.i=!1;this.u=0;this.Mb=null},w7=function(a){a.Mb=g.di(function(){a.Mb=null;
a.i&&!a.u&&(a.i=!1,w7(a))},a.Wf);
var b=a.B;a.B=null;a.C.apply(null,b)},x7=function(){},y7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},A7=function(a){z7.dispatchEvent(new EWa(z7,a))},EWa=function(a,b){g.re.call(this,"statevent",a);
this.stat=b},B7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.Jl(this);this.I=new g.ci;this.I.setInterval(250)},GWa=function(a,b,c){a.Ut=1;
a.jn=Y6(b.clone());a.Cq=c;a.D=!0;FWa(a,null)},C7=function(a,b,c,d,e){a.Ut=1;
a.jn=Y6(b.clone());a.Cq=null;a.D=c;e&&(a.aO=!1);FWa(a,d)},FWa=function(a,b){a.Ht=Date.now();
D7(a);a.No=a.jn.clone();Z6(a.No,"t",a.K);a.HB=0;a.Mf=a.i.ED(a.i.yx()?b:null);0<a.uC&&(a.VA=new v7((0,g.E)(a.gP,a,a.Mf),a.uC));a.C.Ra(a.Mf,"readystatechange",a.WQ);b=a.fp?g.Ue(a.fp):{};a.Cq?(a.FB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Mf.send(a.No,a.FB,a.Cq,b)):(a.FB="GET",a.aO&&!g.dh&&(b.Connection="close"),a.Mf.send(a.No,a.FB,null,b));a.i.Ij(1)},IWa=function(a,b){var c=a.HB,d=b.indexOf("\n",c);
if(-1==d)return E7;c=Number(b.substring(c,d));if(isNaN(c))return HWa;d+=1;if(d+c>b.length)return E7;b=b.substr(d,c);a.HB=d+c;return b},KWa=function(a,b){a.Ht=Date.now();
D7(a);var c=b?window.location.hostname:"";a.No=a.jn.clone();g.kl(a.No,"DOMAIN",c);g.kl(a.No,"t",a.K);try{a.Uj=new ActiveXObject("htmlfile")}catch(m){F7(a);a.Xm=7;A7(22);G7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in H7)f=H7[f];else if(f in JWa)f=H7[f]=JWa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
H7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.ng(g.Gf("b/12014412"),d);a.Uj.open();a.Uj.write(g.jg(c));a.Uj.close();a.Uj.parentWindow.m=(0,g.E)(a.QW,a);a.Uj.parentWindow.d=(0,g.E)(a.kN,a,!0);a.Uj.parentWindow.rpcClose=(0,g.E)(a.kN,a,!1);c=a.Uj.createElement("DIV");a.Uj.parentWindow.document.body.appendChild(c);d=g.Tf(a.No.toString());d=g.Eg(g.Pf(d));d=g.ng(g.Gf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.pg(c,d);a.i.Ij(1)},D7=function(a){a.vH=Date.now()+
a.u;
LWa(a,a.u)},LWa=function(a,b){if(null!=a.ou)throw Error("WatchDog timer not null");
a.ou=y7((0,g.E)(a.XW,a),b)},I7=function(a){a.ou&&(g.C.clearTimeout(a.ou),a.ou=null)},G7=function(a){a.i.vf()||a.zp||a.i.oy(a)},F7=function(a){I7(a);
g.oe(a.VA);a.VA=null;a.I.stop();g.Ll(a.C);if(a.Mf){var b=a.Mf;a.Mf=null;b.abort();b.dispose()}a.Uj&&(a.Uj=null)},J7=function(a,b){try{a.i.dN(a,b),a.i.Ij(4)}catch(c){}},NWa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;MWa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){NWa(a,b,c,d,f)},f)})}},MWa=function(a,b,c){var d=new Image;
d.onload=function(){try{K7(d),c(!0)}catch(e){}};
d.onerror=function(){try{K7(d),c(!1)}catch(e){}};
d.onabort=function(){try{K7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
VVa(d,a)},K7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},OWa=function(a){this.i=a;
this.u=new x7},PWa=function(a){var b=L7(a.i,a.Vu,"/mail/images/cleardot.gif");
Y6(b);NWa(b.toString(),5E3,(0,g.E)(a.JR,a),3,2E3);a.Ij(1)},N7=function(a){var b=a.i.X;
if(null!=b)A7(5),b?(A7(11),M7(a.i,a,!1)):(A7(12),M7(a.i,a,!0));else if(a.rh=new B7(a,void 0,void 0,void 0),a.rh.fp=a.vC,b=a.i,b=L7(b,b.yx()?a.Mu:null,a.wC),A7(5),!g.Dc||g.vc(10))Z6(b,"TYPE","xmlhttp"),C7(a.rh,b,!1,a.Mu,!1);else{Z6(b,"TYPE","html");var c=a.rh;a=!!a.Mu;c.Ut=3;c.jn=Y6(b.clone());KWa(c,a)}},O7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new x7;this.S=a||null;this.X=null!=b?b:null;this.I=c||!1},QWa=function(a,b){this.i=a;
this.map=b;this.context=null},RWa=function(a,b,c,d){g.re.call(this,"timingevent",a);
this.size=b;this.mx=d},SWa=function(a){g.re.call(this,"serverreachability",a)},VWa=function(a){TWa(a);
if(3==a.i){var b=a.Bw++,c=a.cz.clone();g.kl(c,"SID",a.B);g.kl(c,"RID",b);g.kl(c,"TYPE","terminate");P7(a,c);b=new B7(a,a.B,b,void 0);b.Ut=2;b.jn=Y6(c.clone());VVa(new Image,b.jn.toString());b.Ht=Date.now();D7(b)}UWa(a)},WWa=function(a){a.iS(1,0);
a.cz=L7(a,null,a.xC);Q7(a)},TWa=function(a){a.vn&&(a.vn.abort(),a.vn=null);
a.Le&&(a.Le.cancel(),a.Le=null);a.Ml&&(g.C.clearTimeout(a.Ml),a.Ml=null);R7(a);a.Vg&&(a.Vg.cancel(),a.Vg=null);a.Hn&&(g.C.clearTimeout(a.Hn),a.Hn=null)},XWa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new QWa(a.OT++,b));2!=a.i&&3!=a.i||Q7(a)},YWa=function(a){var b=0;
a.Le&&b++;a.Vg&&b++;return b},Q7=function(a){a.Vg||a.Hn||(a.Hn=y7((0,g.E)(a.iN,a),0),a.Cs=0)},$Wa=function(a,b){if(1==a.i){if(!b){a.Bw=Math.floor(1E5*Math.random());
b=a.Bw++;var c=new B7(a,"",b,void 0);c.fp=a.jk;var d=S7(a),e=a.cz.clone();g.kl(e,"RID",b);g.kl(e,"CVER","1");P7(a,e);GWa(c,e,d);a.Vg=c;a.i=2}}else 3==a.i&&(b?ZWa(a,b):0==a.u.length||a.Vg||ZWa(a))},ZWa=function(a,b){if(b)if(6<a.Ap){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Bw-1;b=S7(a)}else c=b.S,b=b.Cq;else c=a.Bw++,b=S7(a);var d=a.cz.clone();g.kl(d,"SID",a.B);g.kl(d,"RID",c);g.kl(d,"AID",a.Xs);P7(a,d);c=new B7(a,a.B,c,a.Cs+1);c.fp=a.jk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vg=c;GWa(c,d,b)},P7=function(a,b){a.Nf&&(a=a.Nf.BK())&&g.ze(a,function(c,d){g.kl(b,d,c)})},S7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Ap&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={gr:e.gr},f++){e.gr=a.u[f].i;var h=a.u[f].map;e.gr=6>=a.Ap?f:e.gr-d;try{g.ze(h,function(l){return function(m,n){c.push("req"+l.gr+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.gr+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},aXa=function(a){a.Le||a.Ml||(a.K=1,a.Ml=y7((0,g.E)(a.hN,a),0),a.Wr=0)},T7=function(a){if(a.Le||a.Ml||3<=a.Wr)return!1;
a.K++;a.Ml=y7((0,g.E)(a.hN,a),bXa(a,a.Wr));a.Wr++;return!0},M7=function(a,b,c){a.DB=c;
a.lk=b.Bl;a.I||WWa(a)},R7=function(a){null!=a.Ip&&(g.C.clearTimeout(a.Ip),a.Ip=null)},bXa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U7=function(a,b){if(2==b||9==b){var c=null;
a.Nf&&(c=null);var d=(0,g.E)(a.ZX,a);c||(c=new g.cl("//www.google.com/images/cleardot.gif"),Y6(c));MWa(c.toString(),1E4,d)}else A7(2);cXa(a,b)},cXa=function(a,b){a.i=0;
a.Nf&&a.Nf.PJ(b);UWa(a);TWa(a)},UWa=function(a){a.i=0;
a.lk=-1;if(a.Nf)if(0==a.C.length&&0==a.u.length)a.Nf.rD();else{g.bc(a.C);var b=g.bc(a.u);a.C.length=0;a.u.length=0;a.Nf.rD(b)}},L7=function(a,b,c){var d=g.El(c);
if(""!=d.i)b&&g.el(d,b+"."+d.i),g.fl(d,d.B);else{var e=window.location;d=dWa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Cv&&g.ze(a.Cv,function(f,h){g.kl(d,h,f)});
g.kl(d,"VER",a.Ap);P7(a,d);return d},dXa=function(){},eXa=function(){this.i=[];
this.u=[]},fXa=function(a,b){this.action=a;
this.params=b||{}},V7=function(a,b){g.G.call(this);
this.i=new g.L(this.HW,0,this);g.I(this,this.i);this.Wf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.E)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.E)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},W7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.I=b;this.B=new g.Is;this.u=new V7(this.BX,this);this.i=null;this.Z=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.oa=d;this.Ba=e},gXa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.DB,sessionId:a.i.B,arrayId:a.i.Xs}},hXa=function(a,b){a.S=b||0;
a.u.stop();X7(a);a.i&&(3==a.i.getState()&&$Wa(a.i),VWa(a.i));a.S=0},Y7=function(a){return!!a.i&&3==a.i.getState()},X7=function(a){if(a.i){var b=a.oa(),c=a.i.jk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.jk=c}},Z7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Si(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ti(a)||"";a=g.vb();0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.tb(a,"10.0")&&(this.u=!1))},$7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.dj(c+b,{})},a8=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.C,d,!0),onError:g.Qa(a.B,e),onTimeout:g.Qa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Du(b,a)},lXa=function(){var a=iXa;
jXa();b8.push(a);kXa()},c8=function(a,b){jXa();
var c=mXa(a,String(b));g.Wb(b8)?nXa(c):(kXa(),g.mc(b8,function(d){d(c)}))},jXa=function(){b8||(b8=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",b8,void 0))},nXa=function(a){var b=(d8+1)%50;
d8=b;e8[b]=a;f8||(f8=49==b)},kXa=function(){var a=b8;
if(e8[0]){var b=f8?d8:-1;do{b=(b+1)%50;var c=e8[b];g.mc(a,function(d){d(c)})}while(b!=d8);
e8=Array(50);d8=-1;f8=!1}},mXa=function(a,b){var c=(Date.now()-oXa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g8=function(a){g.R.call(this);
this.I=a;this.screens=[]},pXa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},qXa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.hq(a.screens,function(f){return!!i7(b,f)});
for(var d=0,e=b.length;d<e;d++)c=pXa(a,b[d])||c;return c},rXa=function(a,b){var c=a.screens.length;
a.screens=g.hq(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},h8=function(a,b,c,d,e){g.R.call(this);
this.B=a;this.K=b;this.C=c;this.I=d;this.D=e;this.u=0;this.i=null;this.Mb=NaN},j8=function(a){g8.call(this,"LocalScreenService");
this.u=a;this.i=NaN;i8(this);this.info("Initializing with "+g7(this.screens))},sXa=function(a){if(a.screens.length){var b=g.Vn(a.screens,function(d){return d.id}),c=$7(a.u,"/pairing/get_lounge_token_batch");
a8(a.u,c,{screen_ids:b.join(",")},(0,g.E)(a.JS,a),(0,g.E)(a.IS,a))}},i8=function(a){if(g.P("deprecate_pair_servlet_enabled"))return qXa(a,[]);
var b=jWa(pWa());b=g.hq(b,function(c){return!c.uuid});
return qXa(a,b)},k8=function(a,b){rWa(g.Vn(a.screens,hWa));
b&&qWa()},m8=function(a,b){g.R.call(this);
this.I=b;b=(b=g.Ry("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.Ub(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;l8("Initialized with "+g.Ji(this.i))},n8=function(a,b,c){var d=$7(a.D,"/pairing/get_screen_availability");
a8(a.D,d,{lounge_token:b.token},(0,g.E)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.E)(function(){c(!1)},a))},o8=function(a,b){a:if($6(b)!=$6(a.i))var c=!1;
else{c=g.Je(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(l8("Updated online screens: "+g.Ji(a.i)),a.i=b,a.ea("screenChange"));tXa(a)},p8=function(a){isNaN(a.B)||g.uu(a.B);
a.B=g.ru((0,g.E)(a.nG,a),0<a.C&&a.C<g.Ra()?2E4:1E4)},l8=function(a){c8("OnlineScreenService",a)},uXa=function(a){var b={};
g.mc(a.I(),function(c){c.token?b[c.token]=c.id:this.me("Requesting availability of screen w/o lounge token.")});
return b},tXa=function(a){a=g.Je(g.Ce(a.i,function(b){return b}));
g.jc(a);a.length?g.Qy("yt-remote-online-screen-ids",a.join(","),60):g.Sy("yt-remote-online-screen-ids")},q8=function(a,b){b=void 0===b?!1:b;
g8.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};vXa(this)},xXa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Hh(),l=c?j7(h,c):null;c&&(a.K||l)||(l=j7(h,b));if(l){l.uuid=b;var m=r8(a,l);n8(a.i,m,function(n){e(n?m:null)})}else c?wXa(a,c,(0,g.E)(function(n){var p=r8(this,new d7({name:d,
screenId:c,loungeToken:n,dialId:b||""}));n8(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},yXa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},zXa=function(a,b,c){n8(a.i,b,c)},wXa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Du($7(a.C,"/pairing/get_lounge_token_batch"),e)},AXa=function(a){a.screens=a.u.Hh();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+g7(a.screens))},vXa=function(a){s8(a);
a.u=new j8(a.C);a.u.subscribe("screenChange",(0,g.E)(a.SS,a));AXa(a);a.K||(a.B=jWa(g.Ry("yt-remote-automatic-screen-cache")||[]));s8(a);a.info("Initializing automatic screens: "+g7(a.B));a.i=new m8(a.C,(0,g.E)(a.Hh,a,!0));a.i.subscribe("screenChange",(0,g.E)(function(){this.ea("onlineScreenChange")},a))},r8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=j7(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||BXa(a));s8(a);a.D[b.uuid]=b.id;g.Qy("yt-remote-device-id-map",a.D,31536E3);return b},BXa=function(a){a=g.hq(a.B,function(b){return"shortLived"!=b.idType});
g.Qy("yt-remote-automatic-screen-cache",g.Vn(a,hWa))},s8=function(a){a.D=g.Ry("yt-remote-device-id-map")||{}},t8=function(a,b,c){g.R.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},u8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},CXa=function(a,b){a.C&&(a.C.token=b,r8(a.B,a.C));
a.ea("sessionScreen",a.C)},v8=function(a,b){c8(a.Ba,b)},w8=function(a,b,c){t8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.oa=(0,g.E)(this.bR,this);this.Aa=(0,g.E)(this.bX,this);this.Z=g.ru(function(){DXa(d,null)},12E4);
this.K=this.D=this.I=this.S=0;this.xa=!1;this.X="unknown"},x8=function(a,b){g.uu(a.K);
a.K=0;0==b?EXa(a):a.K=g.ru(function(){EXa(a)},b)},EXa=function(a){FXa(a,"getLoungeToken");
g.uu(a.D);a.D=g.ru(function(){GXa(a,null)},3E4)},FXa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Ji(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.E)(function(){v8(this,"Failed to send message: "+b+".")},a)):v8(a,"Sending yt message without session: "+g.Ji(c))},y8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.OK(b,function(c){u8(a,c)},function(){return a.zg()},5)):a.zg(Error("Waiting for session status timed out."))},IXa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);HXa(a,d,function(e){e?(a.xa=!0,r8(a.B,d),u8(a,d),a.X="unknown",x8(a,c)):(g.bu(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.zg())},5)},DXa=function(a,b){g.uu(a.Z);
a.Z=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?IXa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.bu(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),y8(a,b.screenId))):(g.bu(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),y8(a,b.screenId)):y8(a,b.screenId):a.zg(Error("Waiting for session status timed out."))},GXa=function(a,b){g.uu(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,x8(a,3E4)):(CXa(a,b.loungeToken),a.xa=!1,a.X="unknown",x8(a,b.loungeTokenRefreshIntervalMs))},HXa=function(a,b,c,d){g.uu(a.I);
a.I=0;zXa(a.B,b,function(e){e||0>d?c(e):a.I=g.ru(function(){HXa(a,b,c,d-1)},300)})},JXa=function(a){g.uu(a.S);
a.S=0;g.uu(a.I);a.I=0;g.uu(a.Z);a.Z=0;g.uu(a.D);a.D=0;g.uu(a.K);a.K=0},z8=function(a,b,c,d){t8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.La=c;this.Ka=null;this.Z=g.Ia;this.X=NaN;this.Ia=(0,g.E)(this.cR,this);this.D=g.Ia;this.K=this.I=0;this.oa=!1;this.xa="unknown"},A8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},KXa=function(a){a.D=a.B.zI(a.Aa,a.i.label,a.i.friendlyName,A8(a),function(b,c){a.D=g.Ia;
a.oa=!0;u8(a,b);"shortLived"==b.idType&&0<c&&B8(a,c)},function(b){a.D=g.Ia;
a.zg(b)})},LXa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.La;uWa()&&(b.env_useStageMdx=1);return g.bj(b)},C8=function(a){return new Promise(function(b){a.Aa=h7();
if(a.Ka){var c=new chrome.cast.DialLaunchResponse(!0,LXa(a));b(c);KXa(a)}else a.Z=function(){g.uu(a.X);a.Z=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,LXa(a));b(d);KXa(a)},a.X=g.ru(function(){a.Z()},100)})},NXa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);return(new Promise(function(e){MXa(a,d,function(f){f?(a.oa=!0,r8(a.B,d),u8(a,d),B8(a,c)):g.bu(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):C8(a)})},OXa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){xXa(a.B,c,b,d,function(f){f&&f.token&&u8(a,f);e(f)},function(f){v8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):C8(a)})},MXa=function(a,b,c,d){g.uu(a.I);
a.I=0;zXa(a.B,b,function(e){e||0>d?c(e):a.I=g.ru(function(){MXa(a,b,c,d-1)},300)})},B8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
A8(a)&&(g.uu(a.K),a.K=0,0==b?PXa(a):a.K=g.ru(function(){PXa(a)},b))},PXa=function(a){A8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,B8(a,3E4)):(a.oa=!1,a.xa="unknown",CXa(a,b.loungeToken),B8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";B8(a,3E4)})},QXa=function(a){g.uu(a.I);
a.I=0;g.uu(a.K);a.K=0;a.D();a.D=function(){};
g.uu(a.X)},D8=function(a,b){t8.call(this,a,b,"ManualSession");
this.u=g.ru((0,g.E)(this.Ys,this,null),150)},E8=function(a,b){g.R.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.I=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.E)(this.TV,this)},RXa=function(a,b){return b?g.Rb(a.B,function(c){return e7(b,c.label)},a):null},F8=function(a){c8("Controller",a)},iXa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G8=function(a){return a.K||!!a.B.length||!!a.i},H8=function(a,b,c){b!=a.i&&(g.oe(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.E)(a.gN,a,b)),b.subscribe("sessionFailed",function(){return SXa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Ys(null)):a.ea("yt-remote-cast2-session-change",null))},SXa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},TXa=function(a){var b=a.u.yI(),c=a.i&&a.i.i;
a=g.Vn(b,function(d){c&&e7(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=RXa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},YXa=function(a,b,c,d){d.disableCastApi?I8("Cannot initialize because disabled by Mdx config."):UXa()?VXa(b,d)&&(J8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?WXa(a,c):(window.__onGCastApiAvailable=function(e,f){e?WXa(a,c):(K8("Failed to load cast API: "+f),L8(!1),J8(!1),g.Sy("yt-remote-cast-available"),g.Sy("yt-remote-cast-receiver"),
XXa(),c(!1))},d.loadCastApiSetupScript?g.Uy("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=q7()&&BWa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?s7():89<=q7()?DWa():(t7(),r7(CWa.map(yWa))))):I8("Cannot initialize because not running Chrome")},XXa=function(){I8("dispose");
var a=M8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);ZXa(!1);g.Nv(N8);N8.length=0},O8=function(){return!!g.Ry("yt-remote-cast-installed")},$Xa=function(){var a=g.Ry("yt-remote-cast-receiver");
return a?a.friendlyName:null},aYa=function(){I8("clearCurrentReceiver");
g.Sy("yt-remote-cast-receiver")},bYa=function(){return O8()?M8()?M8().getCastSession():(K8("getCastSelector: Cast is not initialized."),null):(K8("getCastSelector: Cast API is not installed!"),null)},Q8=function(){O8()?M8()?P8()?(I8("Requesting cast selector."),M8().requestSession()):(I8("Wait for cast API to be ready to request the session."),N8.push(g.Mv("yt-remote-cast2-api-ready",Q8))):K8("requestCastSelector: Cast is not initialized."):K8("requestCastSelector: Cast API is not installed!")},R8=
function(a,b){P8()?M8().setConnectedScreenStatus(a,b):K8("setConnectedScreenStatus called before ready.")},UXa=function(){var a=0<=g.vb().search(/ (CrMo|Chrome|CriOS)\//);
return g.Rj||a},cYa=function(a,b){M8().init(a,b)},VXa=function(a,b){var c=!1;
M8()||(a=new E8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Qy("yt-remote-cast-available",d);b7("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){I8("onReceiverSelected: "+d.friendlyName);
g.Qy("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){I8("onReceiverResumed: "+d.friendlyName);
g.Qy("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){I8("onSessionChange: "+f7(d));
d||g.Sy("yt-remote-cast-receiver");b7("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
I8("cloudview.createSingleton_: "+c);return c},M8=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},WXa=function(a,b){L8(!0);
J8(!1);cYa(a,function(c){c?(ZXa(!0),g.Ov("yt-remote-cast2-api-ready")):(K8("Failed to initialize cast API."),L8(!1),g.Sy("yt-remote-cast-available"),g.Sy("yt-remote-cast-receiver"),XXa());b(c)})},I8=function(a){c8("cloudview",a)},K8=function(a){c8("cloudview",a)},L8=function(a){I8("setCastInstalled_ "+a);
g.Qy("yt-remote-cast-installed",a)},P8=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},ZXa=function(a){I8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},S8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.trackData=null;this.hasNext=this.Pk=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},T8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Pk=!1;a.hasNext=!1;a.K=0;a.I=g.Ra();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},U8=function(a){return a.Hc()?(g.Ra()-a.I)/1E3:0},V8=function(a,b){a.K=b;
a.I=g.Ra()},W8=function(a){switch(a.playerState){case 1:case 1081:return(g.Ra()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},X8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T8(a)},Y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Ve(a.trackData);b.hasPrevious=a.Pk;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},$8=function(a,b){g.R.call(this);
this.B=0;this.C=a;this.I=[];this.D=new eXa;this.u=this.i=null;this.X=(0,g.E)(this.AU,this);this.K=(0,g.E)(this.Kw,this);this.S=(0,g.E)(this.zU,this);this.Z=(0,g.E)(this.HU,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.DG,this),dYa(this))):c=3;0!=c&&(b?this.DG(c):g.ru((0,g.E)(function(){this.DG(c)},this),0));
(a=bYa())&&Z8(this,a);this.subscribe("yt-remote-cast2-session-change",this.Z)},a9=function(a){return new S8(a.C.getPlayerContextData())},dYa=function(a){g.mc("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.I.push(this.C.subscribe(b,g.Qa(this.RV,b),this))},a)},eYa=function(a){g.mc(a.I,function(b){this.C.unsubscribeByKey(b)},a);
a.I.length=0},b9=function(a){return 1==a.getState()},c9=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},e9=function(a,b,c){var d=a9(a);
V8(d,c);-1E3!=d.playerState&&(d.playerState=b);d9(a,d)},f9=function(a,b,c){a.C.sendMessage(b,c)},d9=function(a,b){eYa(a);
a.C.setPlayerContextData(Y8(b));dYa(a)},Z8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.Kw(null));
a.u=b;a.u&&(c8("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.Kw(a.u.media[0]))},fYa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=a9(a);b.contentId!=d.videoId&&c8("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V8(d,a.i.getEstimatedTime());d9(a,d)}else c8("CP","No cast media video. Ignoring state update.")},g9=function(a,b,c){return(0,g.E)(function(d){this.me("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.me("Retrying "+b+" using MDx browser channel."),f9(this,b,c))},a)},h9=function(a,b,c,d){d=void 0===d?!1:d;
g.R.call(this);this.D=NaN;this.xa=!1;this.S=this.K=this.Z=this.oa=NaN;this.X=[];this.C=this.I=this.B=this.wc=this.i=null;this.Ia=a;this.Ba=d;this.X.push(g.pv(window,"beforeunload",(0,g.E)(this.DS,this)));this.u=[];this.wc=new S8;this.Ka=b.id;this.Aa=b.idType;this.i=gYa(this,c);this.i.subscribe("handlerOpened",this.EU,this);this.i.subscribe("handlerClosed",this.BU,this);this.i.subscribe("handlerError",this.CU,this);this.i.subscribe("handlerMessage",this.DU,this);this.i.hB(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.wc.videoId;g.Ty()&&g.Qy("yt-remote-session-video-id",e)},this)},hYa=function(a){return g.Rb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},i9=function(a){c8("conn",a)},gYa=function(a,b){return new W7($7(a.Ia,"/bc"),b,!1,function(){return a.DI()},"shortLived"==a.Aa)},j9=function(a,b){a.ea("proxyStateChange",b)},iYa=function(a){a.D=g.ru((0,g.E)(function(){i9("Connecting timeout");
this.ys(1)},a),2E4)},k9=function(a){g.uu(a.D);
a.D=NaN},l9=function(a){g.uu(a.oa);
a.oa=NaN},jYa=function(a){m9(a);
a.Z=g.ru((0,g.E)(function(){n9(this,"getNowPlaying")},a),2E4)},m9=function(a){g.uu(a.Z);
a.Z=NaN},lYa=function(a,b){var c=null;
if(b){var d=hYa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ga("yt.mdx.remote.remoteClient_",c,void 0);b&&(k9(a),l9(a));c=Y7(a.i)&&isNaN(a.D);b==c?b&&(j9(a,1),n9(a,"getSubtitlesTrack")):b?(a.NK()&&a.wc.reset(),j9(a,1),n9(a,"getNowPlaying"),kYa(a)):a.ys(1)},mYa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.wc.videoId&&(g.Qe(b.params)?a.wc.trackData=null:a.wc.trackData=b.params,a.ea("remotePlayerChange"))},nYa=function(a,b,c){var d=b.params.videoId||b.params.video_id,e=parseInt(b.params.currentIndex,10);
a.wc.listId=b.params.listId||a.wc.listId;X8(a.wc,d,e);a.ea("remoteQueueChange",c)},pYa=function(a,b){b.params=b.params||{};
nYa(a,b,"NOW_PLAYING_MAY_CHANGE");oYa(a,b);a.ea("autoplayDismissed")},oYa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V8(a.wc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.wc.playerState&&(c=-1E3);a.wc.playerState=c;c=Number(b.params.loadedTime);a.wc.S=isNaN(c)?0:c;a.wc.Qj(Number(b.params.duration));c=a.wc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.wc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.wc.playerState?jYa(a):m9(a);a.ea("remotePlayerChange")},qYa=function(a,b){if(-1E3!=a.wc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.wc.playerState=c;b=parseInt(b.params.currentTime,10);V8(a.wc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},rYa=function(a,b){var c="true"==b.params.muted;
a.wc.volume=parseInt(b.params.volume,10);a.wc.muted=c;a.ea("remotePlayerChange")},sYa=function(a,b){a.I=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},tYa=function(a,b){var c="true"==b.params.hasNext;
a.wc.Pk="true"==b.params.hasPrevious;a.wc.hasNext=c;a.ea("previousNextChange")},kYa=function(a){g.uu(a.S);
a.S=g.ru((0,g.E)(a.ys,a,1),864E5)},n9=function(a,b,c){c?i9("Sending: action="+b+", params="+g.Ji(c)):i9("Sending: action="+b);
a.i.sendMessage(b,c)},o9=function(a){g8.call(this,"ScreenServiceProxy");
this.Ue=a;this.i=[];this.i.push(this.Ue.$_s("screenChange",(0,g.E)(this.gR,this)));this.i.push(this.Ue.$_s("onlineScreenChange",(0,g.E)(this.xV,this)))},xYa=function(a,b){tWa();
if(!p7||!p7.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;lWa();n7();p9||(p9=new Z7(b?b.loungeApiHost:void 0),uWa()&&(p9.i="/api/loungedev"));q9||(q9=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",q9,void 0));uYa();var c=r9();if(!c){var d=new q8(p9,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=r9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Ga("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);YXa(a,d,function(f){f?s9()&&R8(s9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){b7("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),t9("Initializing: "+
g.Ji(b)),u9.push(g.Mv("yt-remote-cast2-api-ready",function(){b7("yt-remote-api-ready")})),u9.push(g.Mv("yt-remote-cast2-availability-change",function(){b7("yt-remote-receiver-availability-change")})),u9.push(g.Mv("yt-remote-cast2-receiver-selected",function(){v9(null);
b7("yt-remote-auto-connect","cast-selector-receiver")})),u9.push(g.Mv("yt-remote-cast2-receiver-resumed",function(){b7("yt-remote-receiver-resumed","cast-selector-receiver")})),u9.push(g.Mv("yt-remote-cast2-session-change",vYa)),u9.push(g.Mv("yt-remote-connection-change",function(f){f?R8(s9(),"YouTube TV"):w9()||(R8(null,null),aYa())})),u9.push(g.Mv("yt-remote-cast2-session-failed",function(){b7("yt-remote-connection-failed")})),a=x9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.P("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),t9(" -- with channel params: "+g.Ji(a)),a?(g.Qy("yt-remote-session-app",a.app),g.Qy("yt-remote-session-name",a.name)):(g.Sy("yt-remote-session-app"),g.Sy("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),s9()||wYa())}},yYa=function(){var a=r9().Ue.$_gos();
var b=y9();b&&z9()&&(i7(a,b)||a.push(b));return kWa(a)},A9=function(){var a=zYa();
!a&&O8()&&$Xa()&&(a={key:"cast-selector-receiver",name:$Xa()});return a},zYa=function(){var a=yYa(),b=y9();
b||(b=w9());return g.Rb(a,function(c){return b&&e7(b,c.key)?!0:!1})},y9=function(){var a=s9();
if(!a)return null;var b=r9().Hh();return j7(b,a)},vYa=function(a){t9("remote.onCastSessionChange_: "+f7(a));
if(a){var b=y9();if(b&&b.id==a.id){if(R8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))B9&&(B9.token=a),(b=z9())&&b.hB(a)}else b&&C9(),D9(a,1)}else z9()&&C9()},C9=function(){P8()?M8().stopSession():K8("stopSession called before API ready.");
var a=z9();a&&(a.disconnect(1),E9(null))},F9=function(){var a=z9();
return!!a&&3!=a.getProxyState()},t9=function(a){c8("remote",a)},r9=function(){if(!G9){var a=g.Ha("yt.mdx.remote.screenService_");
G9=a?new o9(a):null}return G9},s9=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},AYa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},BYa=function(){return g.Ha("yt.mdx.remote.connectData_")},v9=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},z9=function(){return g.Ha("yt.mdx.remote.connection_")},E9=function(a){var b=z9();
v9(null);a||AYa("");g.Ga("yt.mdx.remote.connection_",a,void 0);q9&&(g.mc(q9,function(c){c(a)}),q9.length=0);
b&&!a?b7("yt-remote-connection-change",!1):!b&&a&&b7("yt-remote-connection-change",!0)},w9=function(){var a=g.Ty();
if(!a)return null;var b=r9();if(!b)return null;b=b.Hh();return j7(b,a)},D9=function(a,b){s9();
y9()&&y9();if(H9)B9=a;else{AYa(a.id);var c=g.Ha("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new h9(p9,a,x9(),c);a.connect(b,BYa());a.subscribe("beforeDisconnect",function(d){b7("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){z9()&&(z9(),E9(null))});
a.subscribe("browserChannelAuthError",function(){var d=y9();d&&"shortLived"==d.idType&&(P8()?M8().handleBrowserChannelAuthError():K8("refreshLoungeToken called before API ready."))});
E9(a)}},wYa=function(){var a=w9();
a?(t9("Resume connection to: "+f7(a)),D9(a,0)):(o7(),aYa(),t9("Skipping connecting because no session screen found."))},uYa=function(){var a=x9();
if(g.Qe(a)){a=m7();var b=g.Ry("yt-remote-session-name")||"",c=g.Ry("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},x9=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},I9=function(a,b,c){g.G.call(this);
var d=this;this.u=a;this.J=b;this.Ub=c;this.events=new g.LC(this);this.Z=this.events.T(this.J,"onVolumeChange",function(e){CYa(d,e)});
this.D=!1;this.I=new g.rJ(64);this.i=new g.L(this.nO,500,this);this.B=new g.L(this.oO,1E3,this);this.S=new u7(this.rY,0,this);this.C={};this.X=new g.L(this.WO,1E3,this);this.K=new v7(this.seekTo,1E3,this);this.oa=g.Ia;g.I(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.hV);this.events.T(b,"captionschanged",this.xU);this.events.T(b,"captionssettingschanged",this.uO);this.events.T(b,"videoplayerreset",this.AA);this.events.T(b,"mdxautoplaycancel",function(){d.Ub.kK()});
a=this.Ub;a.isDisposed();a.subscribe("proxyStateChange",this.cN,this);a.subscribe("remotePlayerChange",this.Ow,this);a.subscribe("remoteQueueChange",this.AA,this);a.subscribe("previousNextChange",this.ZM,this);a.subscribe("nowAutoplaying",this.TM,this);a.subscribe("autoplayDismissed",this.vM,this);g.I(this,this.i);g.I(this,this.B);g.I(this,this.S);g.I(this,this.X);g.I(this,this.K);this.uO();this.AA();this.Ow()},CYa=function(a,b){if(J9(a)){a.Ub.unsubscribe("remotePlayerChange",a.Ow,a);
var c=Math.round(b.volume);b=!!b.muted;var d=a9(a.Ub);if(c!==d.volume||b!==d.muted)a.Ub.setVolume(c,b),a.X.start();a.Ub.subscribe("remotePlayerChange",a.Ow,a)}},DYa=function(a){a.Xb(0);
a.i.stop();a.Vb(new g.rJ(64))},K9=function(a,b){if(J9(a)&&!a.D){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Xe(c,b));a.Ub.CI(a.J.getVideoData(1).videoId,c);a.C=a9(a.Ub).trackData}},L9=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Ub.playVideo(c.videoId,b,d,e,c.playerParams,c.Za,aWa(c));a.Vb(new g.rJ(1))},EYa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{lL:1});
c&&c.length?(a.J.setOption("captions","track",b),a.D=!1):(a.J.loadModule("captions"),a.D=!0)}else a.J.setOption("captions","track",{})},J9=function(a){return a9(a.Ub).videoId===a.J.getVideoData(1).videoId},M9=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",va:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",va:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ja:["ytp-button","ytp-mdx-privacy-popup-cancel"],va:"Cancel"},{G:"button",Ja:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],va:"Confirm"}]}]}]});this.i=new g.XK(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},N9=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.iwa()]},{G:"div",L:"ytp-remote-display-status-text",va:"{{statustext}}"}]}]});this.api=a;this.i=new g.XK(this,250);g.I(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);FYa(this,a.Ab())},FYa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.T(b,128)?g.CH("Error on $RECEIVER_NAME",c):b.Hc()||g.T(b,4)?g.CH("Playing on $RECEIVER_NAME",c):g.CH("Connected to $RECEIVER_NAME",c);a.Pa("statustext",b);a.i.show()}else a.i.hide()},O9=function(a,b){g.yP.call(this,"Play on",0,a,b);
this.J=a;this.Ko={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},P9=function(a){g.EM.call(this,a);
this.Xk={key:h7(),name:"This computer"};this.ji=null;this.subscriptions=[];this.bG=this.Ub=null;this.Ko=[this.Xk];this.zn=this.Xk;this.Dd=new g.rJ(64);this.KL=0;this.zf=-1;this.Ww=!1;this.Uw=this.Ct=null;if(!g.vE(this.player.V())&&!g.wE(this.player.V())){a=this.player;var b=g.hM(a);b&&(b=b.Pn())&&(b=new O9(a,b),g.I(this,b));b=new N9(a);g.I(this,b);g.rM(a,b.element,4);this.Ct=new M9;g.I(this,this.Ct);g.rM(a,this.Ct.element,4);this.Ww=!!w9()}},Q9=function(a){a.Uw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Uw),a.Uw=null)},GYa=function(a,b,c){a.Dd=c;
a.player.ea("presentingplayerstatechange",new g.lH(c,b))},R9=function(a,b){if(b.key!==a.zn.key)if(b.key===a.Xk.key)C9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.Ww||!a.Ct);(c?0:g.LE(a.player.V())||g.OE(a.player.V()))&&HYa(a);a.zn=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.wE(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.yM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Za,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=aWa(c))&&(a.locationInfo=c)}t9("Connecting to: "+g.Ji(b));"cast-selector-receiver"==b.key?(v9(a||null),b=a||null,P8()?M8().setLaunchParams(b):K8("setLaunchParams called before ready.")):!a&&F9()&&
s9()==b.key?b7("yt-remote-connection-change",!0):(C9(),v9(a||null),a=r9().Hh(),(b=j7(a,b.key))&&D9(b,1))}}},HYa=function(a){a.player.Ab().Hc()?a.player.pauseVideo():(a.Uw=function(b){!a.Ww&&g.nH(b,8)&&(a.player.pauseVideo(),Q9(a))},a.player.addEventListener("presentingplayerstatechange",a.Uw));
a.Ct&&a.Ct.xd();z9()||(H9=!0)},JWa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},H7={"'":"\\'"},gWa={MZ:"atp",qaa:"ska",W9:"que",N7:"mus",paa:"sus",O3:"dsp",u$:"seq",q7:"mic",H2:"dpa",b_:"cds",L7:"mlm",E2:"dsdtr"};c7.prototype.equals=function(a){return a?this.id==a.id:!1};
var p7,l7="",AWa=vWa("loadCastFramework")||vWa("loadCastApplicationFramework"),CWa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(u7,g.G);g.k=u7.prototype;g.k.UQ=function(a){this.C=arguments;this.i=!1;this.Mb?this.B=g.Ra()+this.Wf:this.Mb=g.di(this.D,this.Wf)};
g.k.stop=function(){this.Mb&&(g.C.clearTimeout(this.Mb),this.Mb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.I.apply(null,this.C)))};
g.k.ya=function(){this.stop();u7.le.ya.call(this)};
g.k.VQ=function(){this.Mb&&(g.C.clearTimeout(this.Mb),this.Mb=null);this.B?(this.Mb=g.di(this.D,this.B-g.Ra()),this.B=null):this.u?this.i=!0:(this.i=!1,this.I.apply(null,this.C))};g.w(v7,g.G);g.k=v7.prototype;g.k.xI=function(a){this.B=arguments;this.Mb||this.u?this.i=!0:w7(this)};
g.k.stop=function(){this.Mb&&(g.C.clearTimeout(this.Mb),this.Mb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Mb||(this.i=!1,w7(this))};
g.k.ya=function(){g.G.prototype.ya.call(this);this.stop()};x7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
x7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var z7=new g.pf;g.w(EWa,g.re);g.k=B7.prototype;g.k.fp=null;g.k.Om=!1;g.k.ou=null;g.k.vH=null;g.k.Ht=null;g.k.Ut=null;g.k.jn=null;g.k.No=null;g.k.Cq=null;g.k.Mf=null;g.k.HB=0;g.k.Uj=null;g.k.FB=null;g.k.Xm=null;g.k.Lu=-1;g.k.aO=!0;g.k.zp=!1;g.k.uC=0;g.k.VA=null;var HWa={},E7={};g.k=B7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.WQ=function(a){a=a.target;var b=this.VA;b&&3==g.qj(a)?b.xI():this.gP(a)};
g.k.gP=function(a){try{if(a==this.Mf)a:{var b=g.qj(this.Mf),c=this.Mf.u,d=this.Mf.getStatus();if(g.Dc&&!g.vc(10)||g.dh&&!g.uc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.vj(this.Mf))break a;this.zp||4!=b||7==c||(8==c||0>=d?this.i.Ij(3):this.i.Ij(2));I7(this);var e=this.Mf.getStatus();this.Lu=e;var f=g.vj(this.Mf);if(this.Om=200==e){4==b&&F7(this);if(this.D){for(a=!0;!this.zp&&this.HB<f.length;){var h=IWa(this,f);if(h==E7){4==b&&(this.Xm=4,A7(15),a=!1);break}else if(h==HWa){this.Xm=4;A7(16);a=!1;
break}else J7(this,h)}4==b&&0==f.length&&(this.Xm=1,A7(17),a=!1);this.Om=this.Om&&a;a||(F7(this),G7(this))}else J7(this,f);this.Om&&!this.zp&&(4==b?this.i.oy(this):(this.Om=!1,D7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Xm=3,A7(13)):(this.Xm=0,A7(14)),F7(this),G7(this)}}catch(l){this.Mf&&g.vj(this.Mf)}finally{}};
g.k.QW=function(a){y7((0,g.E)(this.PW,this,a),0)};
g.k.PW=function(a){this.zp||(I7(this),J7(this,a),D7(this))};
g.k.kN=function(a){y7((0,g.E)(this.OW,this,a),0)};
g.k.OW=function(a){this.zp||(F7(this),this.Om=a,this.i.oy(this),this.i.Ij(4))};
g.k.cancel=function(){this.zp=!0;F7(this)};
g.k.XW=function(){this.ou=null;var a=Date.now();0<=a-this.vH?(2!=this.Ut&&this.i.Ij(3),F7(this),this.Xm=2,A7(18),G7(this)):LWa(this,this.vH-a)};
g.k.getLastError=function(){return this.Xm};g.k=OWa.prototype;g.k.vC=null;g.k.rh=null;g.k.WA=!1;g.k.pO=null;g.k.bz=null;g.k.XE=null;g.k.wC=null;g.k.ai=null;g.k.Bl=-1;g.k.Mu=null;g.k.Vu=null;g.k.connect=function(a){this.wC=a;a=L7(this.i,null,this.wC);A7(3);this.pO=Date.now();var b=this.i.S;null!=b?(this.Mu=b[0],(this.Vu=b[1])?(this.ai=1,PWa(this)):(this.ai=2,N7(this))):(Z6(a,"MODE","init"),this.rh=new B7(this,void 0,void 0,void 0),this.rh.fp=this.vC,C7(this.rh,a,!1,null,!0),this.ai=0)};
g.k.JR=function(a){if(a)this.ai=2,N7(this);else{A7(4);var b=this.i;b.lk=b.vn.Bl;U7(b,9)}a&&this.Ij(2)};
g.k.ED=function(a){return this.i.ED(a)};
g.k.abort=function(){this.rh&&(this.rh.cancel(),this.rh=null);this.Bl=-1};
g.k.vf=function(){return!1};
g.k.dN=function(a,b){this.Bl=a.Lu;if(0==this.ai)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.lk=this.Bl;U7(a,2);return}this.Mu=c[0];this.Vu=c[1]}else a=this.i,a.lk=this.Bl,U7(a,2);else if(2==this.ai)if(this.WA)A7(7),this.XE=Date.now();else if("11111"==b){if(A7(6),this.WA=!0,this.bz=Date.now(),a=this.bz-this.pO,!g.Dc||g.vc(10)||500>a)this.Bl=200,this.rh.cancel(),A7(12),M7(this.i,this,!0)}else A7(8),this.bz=this.XE=Date.now(),this.WA=!1};
g.k.oy=function(){this.Bl=this.rh.Lu;if(this.rh.Om)0==this.ai?this.Vu?(this.ai=1,PWa(this)):(this.ai=2,N7(this)):2==this.ai&&((!g.Dc||g.vc(10)?!this.WA:200>this.XE-this.bz)?(A7(11),M7(this.i,this,!1)):(A7(12),M7(this.i,this,!0)));else{0==this.ai?A7(9):2==this.ai&&A7(10);var a=this.i;this.rh.getLastError();a.lk=this.Bl;U7(a,2)}};
g.k.yx=function(){return this.i.yx()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Ij=function(a){this.i.Ij(a)};g.k=O7.prototype;g.k.jk=null;g.k.Cv=null;g.k.Vg=null;g.k.Le=null;g.k.xC=null;g.k.cz=null;g.k.zJ=null;g.k.py=null;g.k.Bw=0;g.k.OT=0;g.k.Nf=null;g.k.Hn=null;g.k.Ml=null;g.k.Ip=null;g.k.vn=null;g.k.DB=null;g.k.Xs=-1;g.k.JL=-1;g.k.lk=-1;g.k.Cs=0;g.k.Wr=0;g.k.Ap=8;g.Sa(RWa,g.re);g.Sa(SWa,g.re);g.k=O7.prototype;g.k.connect=function(a,b,c,d,e){A7(0);this.xC=b;this.Cv=c||{};d&&void 0!==e&&(this.Cv.OSID=d,this.Cv.OAID=e);this.I?(y7((0,g.E)(this.VJ,this,a),100),WWa(this)):this.VJ(a)};
g.k.VJ=function(a){this.vn=new OWa(this);this.vn.vC=this.jk;this.vn.u=this.D;this.vn.connect(a)};
g.k.vf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.iN=function(a){this.Hn=null;$Wa(this,a)};
g.k.hN=function(){this.Ml=null;this.Le=new B7(this,this.B,"rpc",this.K);this.Le.fp=this.jk;this.Le.uC=0;var a=this.zJ.clone();g.kl(a,"RID","rpc");g.kl(a,"SID",this.B);g.kl(a,"CI",this.DB?"0":"1");g.kl(a,"AID",this.Xs);P7(this,a);if(!g.Dc||g.vc(10))g.kl(a,"TYPE","xmlhttp"),C7(this.Le,a,!0,this.py,!1);else{g.kl(a,"TYPE","html");var b=this.Le,c=!!this.py;b.Ut=3;b.jn=Y6(a.clone());KWa(b,c)}};
g.k.dN=function(a,b){if(0!=this.i&&(this.Le==a||this.Vg==a))if(this.lk=a.Lu,this.Vg==a&&3==this.i)if(7<this.Ap){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Ml){if(this.Le)if(this.Le.Ht+3E3<this.Vg.Ht)R7(this),this.Le.cancel(),this.Le=null;else break a;T7(this);A7(19)}}else this.JL=a[1],0<this.JL-this.Xs&&37500>a[2]&&this.DB&&0==this.Wr&&!this.Ip&&(this.Ip=y7((0,g.E)(this.uU,this),6E3));else U7(this,11)}else null!=b&&U7(this,11);else if(this.Le==
a&&R7(this),!g.eb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Xs=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.py=c[2],c=c[3],null!=c?this.Ap=c:this.Ap=6,this.i=3,this.Nf&&this.Nf.RJ(),this.zJ=L7(this,this.yx()?this.py:null,this.xC),aXa(this)):"stop"==c[0]&&U7(this,7):3==this.i&&("stop"==c[0]?U7(this,7):"noop"!=c[0]&&this.Nf&&this.Nf.QJ(c),this.Wr=0)};
g.k.uU=function(){null!=this.Ip&&(this.Ip=null,this.Le.cancel(),this.Le=null,T7(this),A7(20))};
g.k.oy=function(a){if(this.Le==a){R7(this);this.Le=null;var b=2}else if(this.Vg==a)this.Vg=null,b=1;else return;this.lk=a.Lu;if(0!=this.i)if(a.Om)if(1==b){b=Date.now()-a.Ht;var c=z7;c.dispatchEvent(new RWa(c,a.Cq?a.Cq.length:0,b,this.Cs));Q7(this);this.C.length=0}else aXa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.lk)){if(d=1==b)this.Vg||this.Hn||1==this.i||2<=this.Cs?d=!1:(this.Hn=y7((0,g.E)(this.iN,this,a),bXa(this,this.Cs)),this.Cs++,d=!0);d=!(d||2==b&&T7(this))}if(d)switch(c){case 1:U7(this,
5);break;case 4:U7(this,10);break;case 3:U7(this,6);break;case 7:U7(this,12);break;default:U7(this,2)}}};
g.k.iS=function(a){if(!g.Ub(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.ZX=function(a){a?A7(2):(A7(1),cXa(this,8))};
g.k.ED=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.kj;a.S=!1;return a};
g.k.isActive=function(){return!!this.Nf&&this.Nf.isActive(this)};
g.k.Ij=function(a){var b=z7;b.dispatchEvent(new SWa(b,a))};
g.k.yx=function(){return!(!g.Dc||g.vc(10))};
g.k=dXa.prototype;g.k.RJ=function(){};
g.k.QJ=function(){};
g.k.PJ=function(){};
g.k.rD=function(){};
g.k.BK=function(){return{}};
g.k.isActive=function(){return!0};g.k=eXa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.Ub(this.i,a)||g.Ub(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.XPa)(b,a);0<=c?(g.Yb(b,c),b=!0):b=!1;return b||g.Zb(this.u,a)};
g.k.Bi=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Sa(V7,g.G);g.k=V7.prototype;g.k.HW=function(){this.Wf=Math.min(3E5,2*this.Wf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Wf+15E3*Math.random();g.fs(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Wf=5E3};g.Sa(W7,dXa);g.k=W7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.fg=function(a){return this.B.fg(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.Z||(this.Z=!0,g.oe(this.B),hXa(this),g.oe(this.u),this.u=null,this.oa=function(){return""})};
g.k.isDisposed=function(){return this.Z};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new O7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Nf=null);d.Nf=this;this.i=d;X7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.jk||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.jk=f}e?(3!=e.getState()&&0==YWa(e)||e.getState(),this.i.connect(a,b,this.I,e.B,e.Xs)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Xe(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):Y7(this)&&(X7(this),XWa(this.i,a))};
g.k.RJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)XWa(this.i,a[b])}this.ea("handlerOpened")};
g.k.PJ=function(a){var b=2==a&&401==this.i.lk;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.rD=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.BK=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.Xe(a,this.D);return a};
g.k.QJ=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),VWa(this.i)):this.ea("handlerMessage",new fXa(a[0],a[1]))};
g.k.hB=function(a){(this.I.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.jk||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.jk=b}};
g.k.BX=function(){this.u.isActive();0==YWa(this.i)&&this.connect(this.D,this.C)};Z7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z7.prototype.D=function(a){a(Error("request timed out"))};var oXa=Date.now(),b8=null,e8=Array(50),d8=-1,f8=!1;g.Sa(g8,g.R);g8.prototype.Hh=function(){return this.screens};
g8.prototype.contains=function(a){return!!i7(this.screens,a)};
g8.prototype.get=function(a){return a?j7(this.screens,a):null};
g8.prototype.info=function(a){c8(this.I,a)};g.w(h8,g.R);g.k=h8.prototype;g.k.start=function(){!this.i&&isNaN(this.Mb)&&this.uN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Mb)||(g.uu(this.Mb),this.Mb=NaN)};
g.k.ya=function(){this.stop();g.R.prototype.ya.call(this)};
g.k.uN=function(){this.Mb=NaN;this.i=g.Du($7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.E)(this.YQ,this),onError:(0,g.E)(this.XQ,this),onTimeout:(0,g.E)(this.ZQ,this)})};
g.k.YQ=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.I;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new d7(a),b)};
g.k.XQ=function(a){this.i=null;a.status&&404==a.status?this.u>=IYa.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=IYa[this.u],this.Mb=g.ru((0,g.E)(this.uN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.ZQ=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var IYa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(j8,g8);g.k=j8.prototype;g.k.start=function(){i8(this)&&this.ea("screenChange");!g.Ry("yt-remote-lounge-token-expiration")&&sXa(this);g.uu(this.i);this.i=g.ru((0,g.E)(this.start,this),1E4)};
g.k.add=function(a,b){i8(this);pXa(this,a);k8(this,!1);this.ea("screenChange");b(a);a.token||sXa(this)};
g.k.remove=function(a,b){var c=i8(this);rXa(this,a)&&(k8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.BB=function(a,b,c,d){var e=i8(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.ya=function(){g.uu(this.i);j8.le.ya.call(this)};
g.k.JS=function(a){i8(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k8(this,!b);b&&c8(this.I,"Missed "+b+" lounge tokens.")};
g.k.IS=function(a){c8(this.I,"Requesting lounge tokens failed: "+a)};g.w(m8,g.R);g.k=m8.prototype;g.k.start=function(){var a=parseInt(g.Ry("yt-remote-fast-check-period")||"0",10);(this.C=g.Ra()-144E5<a?0:a)?p8(this):(this.C=g.Ra()+3E5,g.Qy("yt-remote-fast-check-period",this.C),this.nG())};
g.k.isEmpty=function(){return g.Qe(this.i)};
g.k.update=function(){l8("Updating availability on schedule.");var a=this.I(),b=g.Ce(this.i,function(c,d){return c&&!!j7(a,d)},this);
o8(this,b)};
g.k.ya=function(){g.uu(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.R.prototype.ya.call(this)};
g.k.nG=function(){g.uu(this.B);this.B=NaN;this.u&&this.u.abort();var a=uXa(this);if($6(a)){var b=$7(this.D,"/pairing/get_screen_availability");this.u=a8(this.D,b,{lounge_token:g.Je(a).join(",")},(0,g.E)(this.lW,this,a),(0,g.E)(this.kW,this))}else o8(this,{}),p8(this)};
g.k.lW=function(a,b){this.u=null;var c=g.Je(uXa(this));if(g.kc(c,g.Je(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;o8(this,c);p8(this)}else this.me("Changing Screen set during request."),this.nG()};
g.k.kW=function(a){this.me("Screen availability failed: "+a);this.u=null;p8(this)};
g.k.me=function(a){c8("OnlineScreenService",a)};g.Sa(q8,g8);g.k=q8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.BB=function(a,b,c,d){this.u.contains(a)?this.u.BB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c8(this.I,a),d(Error(a)))};
g.k.Hh=function(a){return a?this.screens:g.ac(this.screens,g.hq(this.B,function(b){return!this.contains(b)},this))};
g.k.yI=function(){return g.hq(this.Hh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.zI=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new h8(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.oe(l);e(r8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.oe(l);f(m)});
l.start();return(0,g.E)(l.stop,l)};
g.k.aR=function(a,b,c,d){g.Du($7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.E)(function(e,f){e=new d7(f.screen||{});if(!e.name||yXa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);yXa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(r8(this,e))},this),
onError:(0,g.E)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.E)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ya=function(){g.oe(this.u);g.oe(this.i);q8.le.ya.call(this)};
g.k.SS=function(){AXa(this);this.ea("screenChange");this.i.update()};
q8.prototype.dispose=q8.prototype.dispose;g.Sa(t8,g.R);g.k=t8.prototype;g.k.getScreen=function(){return this.C};
g.k.zg=function(a){this.isDisposed()||(a&&(v8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){c8(this.Ba,a)};
g.k.AI=function(){return null};
g.k.CG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.E)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.E)(function(){v8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ya=function(){this.CG("");t8.le.ya.call(this)};g.w(w8,t8);g.k=w8.prototype;g.k.BG=function(a){if(this.u){if(this.u==a)return;v8(this,"Overriding cast session with new session object");JXa(this);this.xa=!1;this.X="unknown";this.u.removeUpdateListener(this.oa);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.oa);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);FXa(this,"getMdxSessionStatus")};
g.k.Ys=function(a){this.info("launchWithParams no-op for Cast: "+g.Ji(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.E)(function(){this.zg()},this),(0,g.E)(function(){this.zg(Error("Failed to stop receiver app."))},this)):this.zg(Error("Stopping cast device without session."))};
g.k.CG=function(){};
g.k.ya=function(){this.info("disposeInternal");JXa(this);this.u&&(this.u.removeUpdateListener(this.oa),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;t8.prototype.ya.call(this)};
g.k.bX=function(a,b){if(!this.isDisposed())if(b)if(b=a7(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Ji(b)),a){case "mdxSessionStatus":DXa(this,b);break;case "loungeToken":GXa(this,b);break;default:v8(this,"Unknown youtube message: "+a)}else v8(this,"Unable to parse message.");else v8(this,"No data in message.")};
g.k.OK=function(a,b,c,d){g.uu(this.S);this.S=0;xXa(this.B,this.i.label,a,this.i.friendlyName,(0,g.E)(function(e){e?b(e):0<=d?(v8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.ru((0,g.E)(this.OK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.AI=function(){return this.u};
g.k.bR=function(a){this.isDisposed()||a||(v8(this,"Cast session died."),this.zg())};g.w(z8,t8);g.k=z8.prototype;g.k.BG=function(a){this.u=a;this.u.addUpdateListener(this.Ia)};
g.k.Ys=function(a){this.Ka=a;this.Z()};
g.k.stop=function(){QXa(this);this.u?this.u.stop((0,g.E)(this.zg,this,null),(0,g.E)(this.zg,this,"Failed to stop DIAL device.")):this.zg()};
g.k.ya=function(){QXa(this);this.u&&this.u.removeUpdateListener(this.Ia);this.u=null;t8.prototype.ya.call(this)};
g.k.cR=function(a){this.isDisposed()||a||(v8(this,"DIAL session died."),this.D(),this.D=g.Ia,this.zg())};g.w(D8,t8);D8.prototype.stop=function(){this.zg()};
D8.prototype.BG=function(){};
D8.prototype.Ys=function(){g.uu(this.u);this.u=NaN;var a=j7(this.B.Hh(),this.i.label);a?u8(this,a):this.zg(Error("No such screen"))};
D8.prototype.ya=function(){g.uu(this.u);this.u=NaN;t8.prototype.ya.call(this)};g.w(E8,g.R);g.k=E8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.I?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.E)(this.WV,this);c=new chrome.cast.ApiConfig(c,(0,g.E)(this.eN,this),e,d,a);c.customDialLaunchCallback=(0,g.E)(this.PU,this);
chrome.cast.initialize(c,(0,g.E)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),lXa(),this.u.subscribe("onlineScreenChange",(0,g.E)(this.BI,this)),this.B=TXa(this),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(f){this.me("Failed to set initial custom receivers: "+g.Ji(f))},this)),this.ea("yt-remote-cast2-availability-change",G8(this)),b(!0))},this),(0,g.E)(function(f){this.me("Failed to initialize API: "+g.Ji(f));
b(!1)},this))};
g.k.FX=function(a,b){F8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)F8("Unsetting old screen status: "+this.i.i.friendlyName),H8(this,null)}if(a&&b){if(!this.i){c=j7(this.u.Hh(),a);if(!c){F8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){F8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=RXa(this,c);a||(F8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(d){this.me("Failed to set initial custom receivers: "+g.Ji(d))},this)));
F8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);H8(this,new D8(this.u,a),!0)}this.i.CG(b)}else F8("setConnectedScreenStatus: no screen.")};
g.k.GX=function(a){this.isDisposed()?this.me("Setting connection data on disposed cast v2"):this.i?this.i.Ys(a):this.me("Setting connection data without a session")};
g.k.eR=function(){this.isDisposed()?this.me("Stopping session on disposed cast v2"):this.i?(this.i.stop(),H8(this,null)):F8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.E)(this.eN,this),(0,g.E)(this.oW,this))};
g.k.ya=function(){this.u.unsubscribe("onlineScreenChange",(0,g.E)(this.BI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=iXa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.Zb(b||[],a);g.oe(this.i);g.R.prototype.ya.call(this)};
g.k.me=function(a){c8("Controller",a)};
g.k.gN=function(a,b){this.i==a&&(b||H8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.TV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)F8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{F8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H8(this,
new D8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H8(this,new z8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:H8(this,new w8(this.u,a,this.config_));break;default:this.me("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.me("Stopping receiver w/o session: "+a.friendlyName)}else this.me("onReceiverAction_ called without receiver.")};
g.k.PU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.me("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.me("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return F8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.me('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H8(this,new z8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,A8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=NXa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.bu(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=OXa(b,c)):a=OXa(b,c)):a=C8(b);return a};
g.k.eN=function(a){var b=this;if(!this.isDisposed()&&!this.I){F8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)F8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),H8(this,new w8(this.u,c,this.config_),!0);else{this.me("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=j7(this.u.Hh(),
d.label);e&&e7(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(F8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.oe(this.i),this.i=new w8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.E)(this.gN,this,this.i)),this.i.subscribe("sessionFailed",function(){return SXa(b,b.i)}),this.i.Ys(null));
this.i.BG(a)}}};
g.k.dR=function(){return this.i?this.i.AI():null};
g.k.oW=function(a){this.isDisposed()||(this.me("Failed to estabilish a session: "+g.Ji(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.WV=function(a){F8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=G8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;G8(this)!=b&&this.ea("yt-remote-cast2-availability-change",G8(this))}};
g.k.BI=function(){this.isDisposed()||(this.B=TXa(this),F8("Updating custom receivers: "+g.Ji(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(){this.me("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",G8(this)))};
E8.prototype.setLaunchParams=E8.prototype.GX;E8.prototype.setConnectedScreenStatus=E8.prototype.FX;E8.prototype.stopSession=E8.prototype.eR;E8.prototype.getCastSession=E8.prototype.dR;E8.prototype.requestSession=E8.prototype.requestSession;E8.prototype.init=E8.prototype.init;E8.prototype.dispose=E8.prototype.dispose;var N8=[];g.k=S8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Pk=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Hc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Qj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+U8(this):this.D};
g.k.clone=function(){return new S8(Y8(this))};g.w($8,g.R);g.k=$8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){b9(this)?(this.i?this.i.play(null,g.Ia,g9(this,"play")):f9(this,"play"),e9(this,1,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.play)};
g.k.pause=function(){b9(this)?(this.i?this.i.pause(null,g.Ia,g9(this,"pause")):f9(this,"pause"),e9(this,2,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.pause)};
g.k.seekTo=function(a){if(b9(this)){if(this.i){var b=a9(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Hc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,g9(this,"seekTo",{newTime:a}))}else f9(this,"seekTo",{newTime:a});e9(this,3,a);this.ea("remotePlayerChange")}else c9(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(b9(this)){this.i?this.i.stop(null,g.Ia,g9(this,"stopVideo")):f9(this,"stopVideo");var a=a9(this);a.index=-1;a.videoId="";T8(a);d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.stop)};
g.k.setVolume=function(a,b){if(b9(this)){var c=a9(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.E)(function(){c8("CP","set receiver volume: "+d)},this),(0,g.E)(function(){this.me("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.E)(function(){c8("CP","set receiver muted: "+b)},this),(0,g.E)(function(){this.me("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f9(this,"setVolume",e)}c.muted=b;c.volume=a;d9(this,c)}else c9(this,g.Qa(this.setVolume,a,b))};
g.k.CI=function(a,b){if(b9(this)){var c=a9(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Ji(b.style),g.Xe(a,c.trackData));f9(this,"setSubtitlesTrack",a);d9(this,c)}else c9(this,g.Qa(this.CI,a,b))};
g.k.setAudioTrack=function(a,b){b9(this)?(b=b.getLanguageInfo().getId(),f9(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=a9(this),a.audioTrackId=b,d9(this,a)):c9(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=a9(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);X8(l,a,c||0);void 0!==b&&(V8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Ji(h));f9(this,"setPlaylist",m);d||d9(this,l)};
g.k.OA=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"previous")}else c9(this,g.Qa(this.OA,a,b))};
g.k.nextVideo=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"next")}else c9(this,g.Qa(this.nextVideo,a,b))};
g.k.Zr=function(){if(b9(this)){f9(this,"clearPlaylist");var a=a9(this);a.reset();d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.Zr)};
g.k.kK=function(){b9(this)?f9(this,"dismissAutoplay"):c9(this,this.kK)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.R.prototype.dispose.call(this)};
g.k.ya=function(){eYa(this);this.C=null;this.D.clear();Z8(this,null);g.R.prototype.ya.call(this)};
g.k.DG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.RV=function(a,b){this.ea(a,b)};
g.k.AU=function(a){if(!a)this.Kw(null),Z8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=a9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c8("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d9(this,b)}};
g.k.Kw=function(a){c8("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),fYa(this),this.ea("remotePlayerChange")};
g.k.zU=function(a){a?(fYa(this),this.ea("remotePlayerChange")):this.Kw(null)};
g.k.ZG=function(){f9(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.HU=function(){var a=bYa();a&&Z8(this,a)};
g.k.me=function(a){c8("CP",a)};g.w(h9,g.R);g.k=h9.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.wc.listId=c);this.wc.videoId=d;this.wc.index=l||0;this.wc.state=3;V8(this.wc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";i9("Connecting with "+c+" and params: "+g.Ji(m));this.i.connect({method:c,params:g.Ji(m)},a,oWa())}else i9("Connecting without params"),this.i.connect({},a,oWa());iYa(this)};
g.k.hB=function(a){this.i.hB(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ga("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),j9(this,3));g.R.prototype.dispose.call(this)};
g.k.ya=function(){k9(this);m9(this);l9(this);g.uu(this.K);this.K=NaN;g.uu(this.S);this.S=NaN;this.B=null;g.qv(this.X);this.X.length=0;this.i.dispose();g.R.prototype.ya.call(this);this.C=this.I=this.u=this.wc=this.i=null};
g.k.DS=function(){this.ys(2)};
g.k.EU=function(){i9("Channel opened");this.xa&&(this.xa=!1,l9(this),this.oa=g.ru((0,g.E)(function(){i9("Timing out waiting for a screen.");this.ys(1)},this),15E3));
sWa(gXa(this.i),this.Ka)};
g.k.BU=function(){i9("Channel closed");isNaN(this.D)?o7(!0):o7();this.dispose()};
g.k.CU=function(a,b){o7();isNaN(this.Tv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),i9("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,i9("Channel error: "+a+" with reconnection in "+this.Tv()+" ms"),j9(this,2))};
g.k.uL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.q(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.DU=function(a){a.params?i9("Received: action="+a.action+", params="+g.Ji(a.params)):i9("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=a7(a.params.devices);this.u=g.Vn(a,function(c){return new c7(c)});
a=!!g.Rb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
lYa(this,a);a=this.uL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.$b(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
lYa(this,!1);break;case "remoteConnected":var b=new c7(a7(a.params.device));g.Rb(this.u,function(c){return c.equals(b)})||bWa(this.u,b);
break;case "remoteDisconnected":b=new c7(a7(a.params.device));g.$b(this.u,function(c){return c.equals(b)});
break;case "gracefulDisconnect":break;case "playlistModified":nYa(this,a,"QUEUE_MODIFIED");break;case "nowPlaying":pYa(this,a);break;case "onStateChange":oYa(this,a);break;case "onAdStateChange":qYa(this,a);break;case "onVolumeChanged":rYa(this,a);break;case "onSubtitlesTrackChanged":mYa(this,a);break;case "nowAutoplaying":sYa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.ea("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":tYa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:i9("Unrecognized action: "+a.action)}};
g.k.vX=function(){if(this.B){var a=this.B;this.B=null;this.wc.videoId!=a&&n9(this,"getNowPlaying")}};
g.k.AS=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Tv())?Y7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.ys=function(a){i9("Disconnecting with "+a);g.Ga("yt.mdx.remote.remoteClient_",null,void 0);k9(this);this.ea("beforeDisconnect",a);1==a&&o7();hXa(this.i,a);this.dispose()};
g.k.yS=function(){var a=this.wc;this.B&&(a=this.wc.clone(),X8(a,this.B,a.index));return Y8(a)};
g.k.HX=function(a){var b=new S8(a);b.videoId&&b.videoId!=this.wc.videoId&&(this.B=b.videoId,g.uu(this.K),this.K=g.ru((0,g.E)(this.vX,this),5E3));var c=[];this.wc.listId==b.listId&&this.wc.videoId==b.videoId&&this.wc.index==b.index||c.push("remoteQueueChange");this.wc.playerState==b.playerState&&this.wc.volume==b.volume&&this.wc.muted==b.muted&&W8(this.wc)==W8(b)&&g.Ji(this.wc.trackData)==g.Ji(b.trackData)||c.push("remotePlayerChange");this.wc.reset(a);g.mc(c,function(d){this.ea(d)},this)};
g.k.NK=function(){var a=this.i.I.id,b=g.Rb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Tv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.vS=function(){return this.C||"UNSUPPORTED"};
g.k.wS=function(){return this.I||""};
g.k.fR=function(){if(!isNaN(this.Tv())){var a=this.i.u;g.gs(a.i);a.start()}};
g.k.EX=function(a,b){n9(this,a,b);kYa(this)};
g.k.DI=function(){var a=g.Nu("SID","")||"",b=g.Nu("SAPISID","")||"",c=g.Nu("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.yc(g.bb(a),2);b=g.yc(g.bb(b),2);c=g.yc(g.bb(c),2);return g.yc(g.bb(a+","+b+","+c),2)};
h9.prototype.subscribe=h9.prototype.subscribe;h9.prototype.unsubscribeByKey=h9.prototype.fg;h9.prototype.getProxyState=h9.prototype.AS;h9.prototype.disconnect=h9.prototype.ys;h9.prototype.getPlayerContextData=h9.prototype.yS;h9.prototype.setPlayerContextData=h9.prototype.HX;h9.prototype.getOtherConnectedRemoteId=h9.prototype.NK;h9.prototype.getReconnectTimeout=h9.prototype.Tv;h9.prototype.getAutoplayMode=h9.prototype.vS;h9.prototype.getAutoplayVideoId=h9.prototype.wS;h9.prototype.reconnect=h9.prototype.fR;
h9.prototype.sendMessage=h9.prototype.EX;h9.prototype.getXsrfToken=h9.prototype.DI;h9.prototype.isCapabilitySupportedOnConnectedDevices=h9.prototype.uL;g.w(o9,g8);g.k=o9.prototype;g.k.Hh=function(a){return this.Ue.$_gs(a)};
g.k.contains=function(a){return!!this.Ue.$_c(a)};
g.k.get=function(a){return this.Ue.$_g(a)};
g.k.start=function(){this.Ue.$_st()};
g.k.add=function(a,b,c){this.Ue.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ue.$_r(a,b,c)};
g.k.BB=function(a,b,c,d){this.Ue.$_un(a,b,c,d)};
g.k.ya=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ue.$_ubk(this.i[a]);this.i.length=0;this.Ue=null;g8.prototype.ya.call(this)};
g.k.gR=function(){this.ea("screenChange")};
g.k.xV=function(){this.ea("onlineScreenChange")};
q8.prototype.$_st=q8.prototype.start;q8.prototype.$_gspc=q8.prototype.aR;q8.prototype.$_gsppc=q8.prototype.zI;q8.prototype.$_c=q8.prototype.contains;q8.prototype.$_g=q8.prototype.get;q8.prototype.$_a=q8.prototype.add;q8.prototype.$_un=q8.prototype.BB;q8.prototype.$_r=q8.prototype.remove;q8.prototype.$_gs=q8.prototype.Hh;q8.prototype.$_gos=q8.prototype.yI;q8.prototype.$_s=q8.prototype.subscribe;q8.prototype.$_ubk=q8.prototype.fg;var B9=null,H9=!1,p9=null,q9=null,G9=null,u9=[];g.w(I9,g.G);g.k=I9.prototype;g.k.ya=function(){g.G.prototype.ya.call(this);this.i.stop();this.B.stop();this.S.stop();this.oa();var a=this.Ub;a.unsubscribe("proxyStateChange",this.cN,this);a.unsubscribe("remotePlayerChange",this.Ow,this);a.unsubscribe("remoteQueueChange",this.AA,this);a.unsubscribe("previousNextChange",this.ZM,this);a.unsubscribe("nowAutoplaying",this.TM,this);a.unsubscribe("autoplayDismissed",this.vM,this);this.Ub=this.u=null};
g.k.zj=function(a){var b=g.Aa.apply(1,arguments);if(2!=this.Ub.B)if(J9(this)){var c=a;if(!a9(this.Ub).isAdPlaying()||"control_seek"!==c)switch(c){case "control_toggle_play_pause":a9(this.Ub).Hc()?this.Ub.pause():this.Ub.play();break;case "control_play":this.Ub.play();break;case "control_pause":this.Ub.pause();break;case "control_seek":this.K.xI(b[0],b[1]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":b=
this.J.getCurrentTime();L9(this,0===b?void 0:b);break;case "control_seek":L9(this,b[0]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}};
g.k.xU=function(a){this.S.UQ(a)};
g.k.rY=function(a){this.zj("control_subtitles_set_track",g.Qe(a)?null:a)};
g.k.uO=function(){var a=this.J.getOption("captions","track");g.Qe(a)||K9(this,a)};
g.k.Xb=function(a){this.u.Xb(a,this.J.getVideoData().lengthSeconds)};
g.k.hV=function(){g.Qe(this.C)||EYa(this,this.C);this.D=!1};
g.k.cN=function(a,b){this.B.stop();2===b&&this.oO()};
g.k.Ow=function(){if(J9(this)){this.i.stop();var a=a9(this.Ub);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.zf=1;break;case 1082:case 1083:this.u.zf=0;break;default:this.u.zf=-1}switch(a.playerState){case 1081:case 1:this.Vb(new g.rJ(8));this.nO();break;case 1085:case 3:this.Vb(new g.rJ(9));break;case 1083:case 0:this.Vb(new g.rJ(2));this.K.stop();this.Xb(this.J.getVideoData().lengthSeconds);break;case 1084:this.Vb(new g.rJ(4));break;case 2:this.Vb(new g.rJ(4));this.Xb(W8(a));
break;case -1:this.Vb(new g.rJ(64));break;case -1E3:this.Vb(new g.rJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a9(this.Ub).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,EYa(this,a));a=a9(this.Ub);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.X.isActive()||this.WO()}else DYa(this)};
g.k.ZM=function(){this.J.ea("mdxpreviousnextchange")};
g.k.AA=function(){J9(this)||DYa(this)};
g.k.TM=function(a){isNaN(a)||this.J.ea("mdxnowautoplaying",a)};
g.k.vM=function(){this.J.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J9(this)&&this.Ub.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a9(this.Ub).playerState?L9(this,a):b&&this.Ub.seekTo(a)};
g.k.WO=function(){var a=this;if(J9(this)){var b=a9(this.Ub);this.events.xc(this.Z);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.Z=this.events.T(this.J,"onVolumeChange",function(c){CYa(a,c)})}};
g.k.nO=function(){this.i.stop();if(!this.Ub.isDisposed()){var a=a9(this.Ub);a.Hc()&&this.Vb(new g.rJ(8));this.Xb(W8(a));this.i.start()}};
g.k.oO=function(){this.B.stop();this.i.stop();var a=this.Ub.C.getReconnectTimeout();2==this.Ub.B&&!isNaN(a)&&this.B.start()};
g.k.Vb=function(a){this.B.stop();var b=this.I;if(!g.wJ(b,a)){var c=g.T(a,2);c!==g.T(this.I,2)&&this.J.Mt(c);this.I=a;GYa(this.u,b,a)}};g.w(M9,g.V);M9.prototype.xd=function(){this.i.show()};
M9.prototype.Db=function(){this.i.hide()};
M9.prototype.u=function(){b7("mdx-privacy-popup-cancel");this.Db()};
M9.prototype.B=function(){b7("mdx-privacy-popup-confirm");this.Db()};g.w(N9,g.V);N9.prototype.onStateChange=function(a){FYa(this,a.state)};g.w(O9,g.yP);O9.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Ko=g.oc(a,this.i,this),g.zP(this,g.Vn(a,this.i)),a=this.J.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Zh(a),this.enable(!0)):this.enable(!1)};
O9.prototype.i=function(a){return a.key};
O9.prototype.rj=function(a){return"cast-selector-receiver"===a?"Cast...":this.Ko[a].name};
O9.prototype.Df=function(a){g.yP.prototype.Df.call(this,a);this.J.setOption("remote","currentReceiver",this.Ko[a]);this.zb.Db()};g.w(P9,g.EM);g.k=P9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.tE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};xYa(b,a);this.subscriptions.push(g.Mv("yt-remote-before-disconnect",this.wU,this));this.subscriptions.push(g.Mv("yt-remote-connection-change",this.XV,this));this.subscriptions.push(g.Mv("yt-remote-receiver-availability-change",this.bN,
this));this.subscriptions.push(g.Mv("yt-remote-auto-connect",this.VV,this));this.subscriptions.push(g.Mv("yt-remote-receiver-resumed",this.UV,this));this.subscriptions.push(g.Mv("mdx-privacy-popup-confirm",this.kX,this));this.subscriptions.push(g.Mv("mdx-privacy-popup-cancel",this.jX,this));this.bN()};
g.k.load=function(){this.player.cancelPlayback();g.EM.prototype.load.call(this);this.ji=new I9(this,this.player,this.Ub);var a=(a=BYa())?a.currentTime:0;var b=F9()?new $8(z9(),void 0):null;0==a&&b&&(a=W8(a9(b)));0!==a&&this.Xb(a);GYa(this,this.Dd,this.Dd);this.player.jl(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.zn=this.Xk;(0,g.pe)(this.ji,this.Ub);this.Ub=this.ji=null;g.EM.prototype.unload.call(this);this.player.jl(5);Q9(this)};
g.k.ya=function(){g.Nv(this.subscriptions);g.EM.prototype.ya.call(this)};
g.k.Yk=function(a){var b=g.Aa.apply(1,arguments);this.loaded&&this.ji.zj.apply(this.ji,[a].concat(g.v(b)))};
g.k.getAdState=function(){return this.zf};
g.k.Pk=function(){return this.Ub?a9(this.Ub).Pk:!1};
g.k.hasNext=function(){return this.Ub?a9(this.Ub).hasNext:!1};
g.k.Xb=function(a,b){this.KL=a||0;this.player.ea("progresssync",a,b);this.player.Oa("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.KL};
g.k.getProgressState=function(){var a=a9(this.Ub),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.wf():!a.isAdPlaying()&&this.player.wf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+U8(a):a.B,isAtLiveHead:1>=(a.u?a.i+U8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+U8(a):a.i,seekableStart:0<
a.C?a.C+U8(a):a.C}};
g.k.nextVideo=function(){this.Ub&&this.Ub.nextVideo()};
g.k.OA=function(){this.Ub&&this.Ub.OA()};
g.k.wU=function(a){1===a&&(this.bG=this.Ub?a9(this.Ub):null)};
g.k.XV=function(){var a=F9()?new $8(z9(),void 0):null;if(a){var b=this.zn;this.loaded&&this.unload();this.Ub=a;this.bG=null;b.key!==this.Xk.key&&(this.zn=b,this.load())}else(0,g.oe)(this.Ub),this.Ub=null,this.loaded&&(this.unload(),(a=this.bG)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.bN=function(){var a=[this.Xk],b=a.concat,c=yYa();O8()&&g.Ry("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Ko=b.call(a,c);a=A9()||this.Xk;R9(this,a);this.player.Oa("onMdxReceiversChange")};
g.k.VV=function(){var a=A9();R9(this,a)};
g.k.UV=function(){this.zn=A9()};
g.k.kX=function(){this.Ww=!0;Q9(this);H9=!1;B9&&D9(B9,1);B9=null};
g.k.jX=function(){this.Ww=!1;Q9(this);R9(this,this.Xk);this.zn=this.Xk;H9=!1;B9=null;this.player.playVideo()};
g.k.mf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Ko;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q8():R9(this,b)),this.loaded?this.zn:this.Xk;case "quickCast":return 2===this.Ko.length&&"cast-selector-receiver"===this.Ko[1].key?(b&&Q8(),!0):!1}};
g.k.ZG=function(){this.Ub.ZG()};
g.k.Wi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.DM("remote",P9);})(_yt_player);
